nda_variables:
  - subjectkey
  - src_subject_id
  - interview_date
  - interview_age
  - sex
  - comments_misc
  - image_file
  - image_thumbnail_file
  - scan_object
  - image_file_format
  - experiment_id
  - image_description
  - mri_field_of_view_pd
  - scan_type
  - data_file2
  - data_file2_type
  - image_extent1
  - image_extent2
  - image_extent3
  - image_extent4
  - extent4_type
  - image_extent5
  - extent5_type
  - image_unit1
  - image_unit2
  - image_unit3
  - image_unit4
  - image_unit5
  - image_resolution1
  - image_resolution2
  - image_resolution3
  - image_resolution4
  - image_slice_thickness
  - image_orientation
  - image_num_dimensions
  - qc_outcome
  - qc_description
  - qc_fail_quest_reason
  - decay_correction
  - frame_end_times
  - frame_end_unit
  - frame_start_times
  - frame_start_unit
  - pet_isotope
  - pet_tracer
  - time_diff_inject_to_image
  - time_diff_units
  - pulse_seq
  - slice_acquisition
  - software_preproc
  - study
  - week
  - experiment_description
  - visit
  - slice_timing
  - bvek_bval_files
  - bvecfile
  - bvalfile
  - deviceserialnumber
  - procdate
  - visnum
  - manifest
  - emission_wavelingth
  - objective_magnification
  - objective_na
  - immersion
  - exposure_time
  - camera_sn
  - block_number
  - level
  - cut_thickness
  - stain
  - stain_details
  - pipeline_stage
  - deconvolved
  - decon_software
  - decon_method
  - psf_type
  - psf_file
  - decon_snr
  - decon_iterations
  - micro_temmplate_name
  - in_stack
  - decon_template_name
  - stack
  - slices
  - slice_number
  - slice_thickness
  - type_of_microscopy
  - excitation_wavelength
  - year_mta
  - image_modality
  - scanner_manufacturer_pd
  - scanner_type_pd
  - scanner_software_versions_pd
  - magnetic_field_strength
  - mri_repetition_time_pd
  - mri_echo_time_pd
  - flip_angle
  - acquisition_matrix
  - patient_position
  - photomet_interpret
  - receive_coil
  - transmit_coil
  - transformation_performed
  - transformation_type
  - image_history
